config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books do
    resources :comments, only: %i[create update edit destroy]
  end

  resources :users
  resource :sessions, only: %i[login create destroy]
  resource :users_books, only: %i[create destroy]
  root 'home#startpage'

  namespace :api do
    namespace :v1 do
      resources :books, only: %i[index show]
    end
  end

  # Defines the root path route ("/")
  get 'home/list'
  get 'sessions/login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { regular: 0, admin: 1 }

  validates :email, presence: true, uniqueness: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP, message: 'invalid format' }
  has_secure_password
  validates :password, format: { with: /\A(?=.*[A-Z])(?=.*[0-9])(?=.*[a-z])/x,
                                 message: 'must be present and contain number, small letter and big letter' },
                       length: { minimum: 5, maximum: 50 },
                       on: :create
  validates :password_confirmation, presence: true,
                                    on: :create
  validates :date_of_birth, presence: true
  validate :date_of_birth_cannot_be_in_the_future
  validate :date_of_birth_cannot_be_more_than_100_years_ago
  validates :nick_name, presence: true, length: { minimum: 2, maximum: 100 }
  validates :description, length: { minimum: 2, maximum: 1000,
                                    too_long: '%<count>s characters is the maximum allowed' },
                          allow_blank: true

  has_many :users_books
  has_many :books, through: :users_books
  has_many :comments

  private

  default_scope { where(deleted: false) }

  def date_of_birth_cannot_be_in_the_future
    return unless date_of_birth.present? && date_of_birth > Date.today

    errors.add(:date_of_birth, "can't be in the future")
  end

  def date_of_birth_cannot_be_more_than_100_years_ago
    return unless date_of_birth.present? && date_of_birth < 100.years.ago

    errors.add(:date_of_birth,
               'can not be more than 100 years ago')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :login_required, only: %i[show update edit destroy]
  before_action :require_admin_or_account_owner, only: %i[edit update destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/:id
  def show
    @books = @user.books.includes(:users_books).where(users_books: { user_id: @user.id })
    @comments = @user.comments.includes(:book)
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to logged_in? ? user_url(User.last) : sessions_login_path, notice: 'User was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/:id
  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: 'User was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/:id
  def destroy
    @user.update(deleted: true)
    redirect_to users_url, notice: 'User was successfully deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :nick_name, :date_of_birth, :description,
                                 :deleted)
  end

  # Checks if the logged in user is the owner or admin to edit/update/delete profile.
  def require_admin_or_account_owner
    return if current_user.id == @user.id || current_user.admin?

    flash[:alert] = 'You must be logged in as this user to view this page.'
    redirect_to users_url
  end
end

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-xl mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex justify-between">
    <div>
      <div class="my-5">
        <%= form.label :email %>
        <%= form.text_field :email, placeholder: "john@mail.pl", class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
      <% if !logged_in? || user.new_record? %>
        <div class="my-5">
          <%= form.label :password %>
          <%= form.password_field :password, placeholder: "password", class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>
        <div class="my-5">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation, placeholder: "password confirmation", class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>
      <% end %>
      <div class="my-5">
        <%= form.label :nick_name %>
        <%= form.text_field :nick_name, placeholder: "john1", class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
      <div class="my-5">
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth, class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
      <div class="my-5">
        <%= form.label :description %>
        <%= form.text_area :description, rows: 4, placeholder: "Write sth about yourself.", class: "shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
    </div>
    <div class="m-auto">
      <%= image_tag("avatar.png", :class => "object-cover h-48 w-36 rounded-lg") %>
    </div>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-xl py-3 px-5 active:bg-blue-800 hover:bg-blue-700 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
  <% if logged_in? %>
    <%= link_to 'Back to users', users_path, class: "whitespace-nowrap active:bg-gray-200 rounded-xl py-3 px-5 bg-white inline-block font-medium mt-3 ml-4" %>
  <% end %>
<% end %>

app/views/users/_show_comments.html.erb
<% unless @user.comments.empty? %>
  <table class="mb-8 rounded-xl flex w-1/2">
    <tbody>
      <% @comments.each do |comment| %>
        <tr class="flex justify-between my-2">
          <td class="grow flex-wrap flex flex-col bg-white rounded-xl">
            <div>
              <p class="p-2"><%= comment.content %></p>
            </div>
            <div class="m-1 p-1">
              <span class="font-light text-xs">Book:</span> <%= link_to comment.book.title, book_path(comment.book), class:"m-1 p-1 bg-gray-100 rounded-xl whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 font-extralight text-xs" %>
            </div>
          </td>
          <td class= "flex flex-col content-end">
            <% if current_user == @user || current_user.admin? %>
              <%= button_to 'Delete comment', book_comment_path(comment.book, comment), method: :delete, class: "m-1 p-1 bg-white rounded-xl whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 font-extralight text-sm" %>
              <%= link_to 'Edit comment', edit_book_comment_path(comment.book, comment), class: "m-1 p-1 bg-white rounded-xl whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 font-extralight text-sm" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="mb-8 py-4 bg-gray-50 rounded-xl"><span class="m-1">Nothing here.</span></p>
<% end %>

app/views/users/_show_table_usersbook_if_empty.html.erb
<table class="my-8 py-4 bg-gray-50 rounded-xl">
  <thead>
    <tr>
      <th><strong class="py-1 inline-block w-36 rounded-xl w-36">My books:</strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="2" class="py-1 my-5">No books added to the collection yet.</td>
    </tr>
  </tbody>
</table>

app/views/users/_show_table_usersbooks.html.erb
<table class="my-8 py-4 bg-gray-50 rounded-xl">
  <thead>
    <tr>
      <th><strong class="py-1 inline-block w-36 rounded-xl w-36">My books:</strong></th>
      <th><strong class="py-1 inline-block w-36 rounded-xl w-36">Action:</strong></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr class="my-5">
        <td>
          <span class="py-1 mx-2" ><%= book.title %></span>
        </td>
        <td>
          <%= button_to "Remove book", users_books_path(id: book.users_books.first.id), method: :delete, class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 m-2 rounded-xl py-3 px-5 bg-white font-medium" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class= "mx-auto md:w-2/3 w-full mb-12 ">
  <div class="bg-gray-100 rounded-3xl py-6 mb-4 mt-12">
    <div class="flex justify-between">
      <div class="w-2/3">
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl px-5 bg-gray-100 w-36">Email:</strong>
          <br>
          <span class="ml-5"><%= user.email %></span>
        </p>
        <p class="my-5">
          <strong class="rounded-xl py-1 inline-block w-36 rounded-xl px-5 bg-gray-100 w-36">Nick name:</strong>
          <br>
          <span class="ml-5"><%= user.nick_name %></span>
        </p>
        <p class="my-5">
          <strong class="rounded-xl py-1 inline-block w-36 rounded-xl px-5 bg-gray-100 w-36">Date of birth:</strong>
          <br>
          <span class="ml-5"><%= user.date_of_birth %></span>
        </p>
        <p class="my-5 ml-5">
          <strong class="rounded-xl py-1 inline-block rounded-xl bg-gray-100 w-36">Description:</strong>
          <br>
          <span class=""><%= user.description %></span>
        </p>
      </div>
      <div class="m-auto w-1/3">
        <%= image_tag("avatar.png", :class => "object-cover h-48 w-36 rounded-lg") %>
      </div>
    </div>
    <div class="flex justify-start">
      <% if logged_in? && current_user == user %>
        <%= link_to 'Edit user', edit_user_path(user), class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 rounded-xl py-3 px-5 bg-white inline-block font-medium ml-4 mt-3" %>
      <% end %>
      <%= link_to "Show this user", user, class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 rounded-xl py-3 px-5 bg-white inline-block font-medium ml-4 mt-3" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full mb-12 bg-gray-100 text-black-500 px-3 py-2 font-medium rounded-3xl mt-20 py-8">
  <h1 class="font-bold text-2xl text-center">Editing user</h1>
  <div class="my-5">
    <%= render "form", user: @user %>
    <%= link_to "Show this user", @user, class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 rounded-xl py-3 px-5 bg-white inline-block font-medium mt-3" %>
    <%= link_to "Show all users", users_path, class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 rounded-xl py-3 px-5 bg-white inline-block font-medium ml-3 mt-3" %>
  </div>
</div>

app/views/users/index.html.erb
<% if logged_in? %>
  <div class="w-full m-auto">
    <div class="flex justify-between items-center mx-auto md:w-2/3 w-full mb-12 bg-gray-100 text-black-500 px-3 py-2 font-medium rounded-3xl mt-20 py-8">
      <h1 class="font-bold text-4xl">Users</h1>
      <div class='flex'>
        <%= link_to 'Sign Up', new_user_path, class: "whitespace-nowrap active:bg-blue-800 hover:bg-blue-700 bg-blue-600 rounded-xl py-3 px-5 text-white block font-medium ml-2" %>
      </div>
    </div>
    <div id="users" class="min-w-full">
      <%= render @users %>
    </div>
  </div>
<% else %>
  <div class="w-full m-auto">
    <div class="mt-40 flex justify-between items-center mx-auto md:w-2/3 w-full mb-12 bg-gray-100 text-black-500 px-3 font-medium rounded-3xl py-32">
      <h1 class="font-bold text-4xl">Users</h1>
      <div class='flex'>
        <%= link_to 'Log In', sessions_login_path, class: "whitespace-nowrap active:bg-blue-800 hover:bg-blue-700 bg-blue-600 rounded-xl py-3 px-5 text-white block font-medium " %>
        <%= link_to 'Sign Up', new_user_path, class: "whitespace-nowrap active:bg-blue-800 hover:bg-blue-700 bg-blue-600 rounded-xl py-3 px-5 text-white block font-medium ml-2" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full mb-12 bg-gray-100 text-black-500 px-3 py-2 font-medium rounded-3xl mt-20 py-8">
  <h1 class="font-bold text-2xl text-center">Sign Up</h1>
  <%= render "form", user: @user %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full mb-12 bg-gray-100 text-black-500 px-3 py-2 font-medium rounded-3xl mt-28 py-8">
  <h1 class="font-bold text-2xl text-center">Show user: <%= @user.nick_name%> </h1>
  <div class="mx-auto">
    <div class="flex justify-between">
      <div class="w-1/2">
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl bg-gray-100 w-36">Email:</strong>
          <br>
          <span><%= @user.email %></span>
        </p>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl bg-gray-100 w-36">Nickname:</strong>
          <br>
          <span><%= @user.nick_name %></span>
        </p>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl bg-gray-100 w-36">Date of birth:</strong>
          <br>
          <span><%= @user.date_of_birth.strftime("%d/%m/%Y") %></span>
        </p>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl bg-gray-100 w-36">Description:</strong>
          <br>
          <span><%= @user.description %></span>
        </p>
        <%= @user.books.empty? ? render('show_table_usersbook_if_empty') : render('show_table_usersbooks') %>
        <p class="mt-5 flex">
          <strong class="py-1 inline-block w-36 rounded-xl bg-gray-100">My comments:</strong>
          <br>
          <span><%= render partial: 'show_comments' %></span>
        </p>
      </div>
      <div class="m-auto flex content-center">
        <%= image_tag("avatar.png", :class => "object-cover h-58 w-36 rounded-lg") %>
      </div>
    </div>
    <div class="flex justify-start flex-wrap">
      <% if logged_in? && (current_user == @user || current_user.admin?) %>
        <%= link_to 'Edit this user', edit_user_path(@user), class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 mt-2 rounded-xl py-3 px-5 bg-white inline-block font-medium" %>
        <%= button_to 'Delete this user', user_path(@user), method: :delete, class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 mt-2 ml-2 rounded-xl py-3 px-5 bg-white font-medium" %>
      <% end %>
      <%= link_to 'Show all users', users_path, class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 mt-2 ml-2 rounded-xl py-3 px-5 bg-white font-medium" %>
    </div>
  </div>
</div>