config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books do
    resources :comments, only: %i[create update edit destroy]
  end

  resources :users
  resource :sessions, only: %i[login create destroy]
  resource :users_books, only: %i[create destroy]
  root 'home#startpage'

  namespace :api do
    namespace :v1 do
      resources :books, only: %i[index show]
    end
  end

  # Defines the root path route ("/")
  get 'home/list'
  get 'sessions/login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
end

app/views/home/_footer.html.erb
<footer class="w-full bg-white fixed left-0 bottom-0 flex justify-center items-center">
  <div class="footer-text">
    <p>2022 Maja Małkiewicz LLInformatics Internship Project</p>
  </div>
</footer>

app/views/home/_header.html.erb
<header class='header-container'>
  <p class='header-logo'>
    <%= link_to 'BOOK STORE', root_path %>
  </p>
  <ul id="list-header">
    <% if logged_in? %>
      <%= link_to 'Books', books_path, class: 'font-light py-2 px-5' %>
      <%= link_to 'Users', users_path, class: 'font-light py-2 px-5' %>
      <%= button_to "Log out", sessions_path, method: :delete, class: 'font-light py-2 px-5' %>
      <%= link_to "Profile", current_user, class: 'font-light py-2 px-5' %>
      <%= image_tag("avatar-2.png", :class => "rounded-full mr-4 object-cover") %>
    <% else %>
      <%= link_to 'Log In', sessions_login_path, class: 'whitespace-nowrap font-light py-2 px-5'%>
      <%= link_to 'Sign Up', new_user_path, class: 'whitespace-nowrap font-light py-2 px-5'%>
    <% end %>
  </ul>
</header>
<%= javascript_include_tag 'header' %>

app/views/home/index.html.erb
<!-- The main page body-->

<div class="home">

  <!-- section 1 --> 
  <section id="section-1" class="bg-gray-100">
    <div class="section-1-text">
      <h2>ABOUT ME</h2>
        <ul class="section-1-list">
          <li>Name: Maja</li>
          <li>City: Warsaw</li>
          <li>Gender: female</li>
        </ul>
    </div>
      <div class="photo">
        <%= image_tag("img", :class => "style_image") %>
      </div>
  </section>

  <!-- section 2 --> 
  <section id="section-2" class="bg-gray-100">
    <div class='column-left'>
      <h2>Lorem Ipsum</h2>
      <h6 id="quotes-container">
      <p id="quote-view">Show quote.</p>
      </h6>
      <div id="lorem-ipsum-text">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque blandit, sapien at porta molestie, elit dolor porta purus, at volutpat nisl leo non libero. Etiam tempus nec nisi ut volutpat. Cras eu sem facilisis, feugiat ante auctor, pellentesque ligula. Maecenas et orci lectus. Suspendisse pellentesque feugiat blandit. Vestibulum ultrices nulla euismod risus gravida volutpat. Maecenas neque augue, aliquet eget est nec, vehicula congue eros. Curabitur lacinia pretium nunc, sit amet pellentesque turpis ultricies id. Fusce quis felis vulputate, rhoncus odio et, semper nibh. Etiam lacinia, arcu eu commodo euismod, quam est fringilla massa, vitae pulvinar sem odio a tellus. Vestibulum vitae dui fringilla, condimentum velit in, placerat odio. Cras dolor arcu, elementum in est vitae, lobortis gravida massa. Cras ac tellus id est pulvinar lobortis.</p>
                
        <p>Vivamus posuere nisi justo. Morbi quis arcu maximus risus facilisis tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed ut lorem at justo condimentum mollis. Nullam justo massa, lobortis ut consectetur vel, interdum at sapien. Morbi venenatis in massa in vulputate. Duis eu nulla lacinia, pharetra metus non, bibendum libero. Morbi leo dui, sagittis ut metus non, lobortis consectetur leo. In elementum, purus pellentesque efficitur placerat, ipsum felis varius tellus, ac rhoncus ante lorem sit amet massa. Nullam at placerat magna. Nunc hendrerit felis a nibh interdum eleifend. Duis sed pulvinar nisi. Ut in iaculis libero. Aenean vel velit non ipsum interdum venenatis. Integer cursus odio nec enim pulvinar sagittis.</p>
            
        <p>Fusce mattis blandit nibh non ultrices. Fusce sed lacinia elit, a condimentum odio. Praesent varius ultrices eros, condimentum ultricies arcu lobortis ut. Phasellus tincidunt tristique elementum. Nulla laoreet gravida est, sed iaculis ex ultrices id. Sed sollicitudin eu risus sed volutpat. Suspendisse potenti. Nulla ultrices ipsum eget commodo mollis.</p>
      </div>
    </div>
    <div class='column-right'>
      <h2>Hobbies:</h2>
      <ul class="hobby-list">
        <li id="li-hobby">Architecture</li>
        <li id="li-hobby">Catan</li>
        <li id="li-hobby">Moutains hiking</li>
        <li id="li-hobby">Programming</li>
        <li id="li-hobby">Skiing</li>
        <li id="li-hobby">Swimming</li>
        <li id="li-hobby">SUP</li>
        <li id="li-hobby">Traveling</li>
        <li id="li-hobby">Yoga</li>
      </ul>
    </div>
  </section>

  <!-- section 3 --> 
  <section id="section-3" class="bg-gray-100">
    <div id='container'>
      <button id='next-button'>
        <%= link_to "Go to To-Do List", home_list_path %>
      </button>
    </div>
  </section>

</div>

<%= javascript_include_tag "index" %>

app/views/home/list.html.erb
<%= stylesheet_link_tag 'home/_to-do-list' %>

<div class="list-page">

<!-- HTML -->
  <div class="the-to-do-list-fiels">
    
    <!-- title -->
    <div id="add-to-do" class="header">
    <h3>My To Do List</h3>
      <div class="input-area">
        <input type="text" id="txt" placeholder="Add task here.">
        <button  type="submit" id="btn" class="add-btn">Add</button>
      </div>
    </div>
    
    <!-- the list -->
    <div class="tasks-field">
      <ul id="ul-of-tasks">
        <li id="task" class="unchecked first-child">
          <input type="checkbox" class="check-box" id="check-box">
            Water the plants
          <button class="del-btn">x</button>
        </li>
        <li id="task" class="unchecked">
          <input type="checkbox" class="check-box">
            Pump up the wheels in the car
          <button class="del-btn">x</button>
        </li>
        <li id="task" class="unchecked">
          <input type="checkbox" class="check-box">
            Check the oil in the car
          <button class="del-btn">x</button>
        </li>
        <li id="task" class="unchecked">
          <input type="checkbox" class="check-box">
            Refill windshield washer fluid
          <button class="del-btn">x</button>      
        </li>   
        <li id="task" class="unchecked last-child">
          <input type="checkbox" class="check-box">
            Take presents
          <button class="del-btn">x</button>      
        </li>
      </ul>
    <br>
    <br>
    </div>
     
    <!-- remove btn -->
    <div class="rmv-btn-class">
      <button class="rmv-btn" type="button" onclick="removeAll()">Remove All</button>
    </div>
        
  </div>
</div>

<%= javascript_include_tag "todolist" %>

app/views/home/startpage.html.erb
<div class="w-full m-auto">
  <div class="flex-wrap flex justify-between items-center mx-auto md:w-2/3 mb-12 bg-gray-100 text-black-500 px-3 font-medium rounded-3xl mt-44 py-32">
    <h1 class="ml-2 mt-2 font-thin text-gray-600 text-4xl">WELCOME TO <span class="text-gray-900 font-bold">BOOK STORE</span></h1>
    <% if logged_in? %>
      <div class="flex-wrap flex justify-between items-center">
        <%= link_to 'Create New User', new_user_path, class: "whitespace-nowrap active:bg-blue-800 hover:bg-blue-700 bg-blue-600 rounded-xl py-3 px-5 text-white font-medium ml-2 mt-2" %>
        <%= link_to "Profile", current_user, class: "active:bg-blue-800 hover:bg-blue-700 bg-blue-600 rounded-xl py-3 px-5 text-white block font-medium ml-2 mt-2" %>
      </div>
    <% else %>
      <div class="flex-wrap flex justify-between items-center">
        <%= link_to 'Log In', sessions_login_path, class: "whitespace-nowrap active:bg-blue-800 hover:bg-blue-700 bg-blue-600 rounded-xl py-3 px-5 text-white block font-medium mt-2" %>
        <%= link_to 'Sign Up', new_user_path, class: "whitespace-nowrap active:bg-blue-800 hover:bg-blue-700 bg-blue-600 rounded-xl py-3 px-5 text-white block font-medium ml-2 mt-2" %>
      </div>
    <% end %>
  </div>
</div>