config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books do
    resources :comments, only: %i[create update edit destroy]
  end

  resources :users
  resource :sessions, only: %i[login create destroy]
  resource :users_books, only: %i[create destroy]
  root 'home#startpage'

  namespace :api do
    namespace :v1 do
      resources :books, only: %i[index show]
    end
  end

  # Defines the root path route ("/")
  get 'home/list'
  get 'sessions/login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  include ImageUploader::Attachment(:image) # adds an `image` virtual attribute
  scope :active, -> { where(deleted: false) }
  validates :title, presence: true,
                    length: { maximum: 100 }
  validates :date_of_publication, presence: true
  validates :pages, presence: true,
                    numericality: { greater_than_or_equal_to: 1 }
  validates :description, presence: true
  validates :deleted, inclusion: { in: [true, false] }
  before_validation :set_default_deleted, on: :create

  has_many :users_books
  has_many :users, through: :users_books
  has_many :comments

  def destroy_with_usersbooks
    transaction do
      self.deleted = true
      users_books.destroy_all
      save!
    end
  end

  private

  def set_default_deleted
    self.deleted ||= false
  end
end

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < ApplicationController
  # GET /api/v1/books
  def index
    render json: BooksResponseService.call(index_params)
  rescue BooksResponseService::InvalidSortingParameterError => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  def show
    render json: BookResponseService.call(params)
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Not found.' }, status: :not_found
  end

  private

  def index_params
    params.permit(:title, :date_of_publication_after, :date_of_publication_since,
                  :date_of_publication, :created_at, :sort)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include SessionsHelper
  before_action :login_required
  before_action :require_admin!, except: %i[index show]
  before_action :set_book, only: %i[show edit update destroy]

  # GET /books
  def index
    @books = Book.all.active
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # POST /books
  def create
    @book = Book.new(book_params)
    if @book.save
      ImageWorker.perform_async(@book.id)
      redirect_to book_url(Book.last), notice: 'Book was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /books/:id
  def update
    if @book.update(book_params)
      redirect_to book_url(@book), notice: 'Book was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /books/:id
  def destroy
    @book.destroy_with_usersbooks
    redirect_to books_url, notice: 'Book was successfully deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :date_of_publication, :pages, :description, :deleted, :image)
  end
end

app/views/books/_book.html.erb
<div class= "mx-auto md:w-2/3 w-full mb-12 ">
  <div class="bg-gray-100 rounded-3xl py-6 mb-4 mt-12">
    <div class="flex justify-between">
      <div>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl px-5 bg-gray-100 w-36">Title:</strong>
          <%= book.title %>
        </p>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl px-5 bg-gray-100 w-36">Date of publication:</strong>
          <%= book.date_of_publication %>
        </p>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl px-5 bg-gray-100 w-36">Pages:</strong>
          <%= book.pages %>
        </p>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl px-5 bg-gray-100 w-36">Description:</strong>
          <%= book.description %>
        </p>
      </div>
      <div class="m-auto mt-28 flex content-center">
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl px-5 bg-gray-100 w-36">Image:</strong>
          <% if book.image_url(:index).present? %>
            <%= image_tag book.image_url(:index), class: "object-cover h-58 w-36 rounded-lg" %>
          <% else %>
            <%= image_tag("book.jpeg", class: "object-cover h-58 w-36 rounded-lg") %>
          <% end %>
        </p>
      </div>
    </div>
    <% if action_name != "show" %>
      <%= link_to "Show this book", book, class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 rounded-xl py-3 px-5 bg-white inline-block font-medium ml-4 mt-3" %>
      <% if current_user.admin? %>
        <%= link_to 'Edit this book', edit_book_path(book), class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 rounded-xl py-3 px-5 bg-white inline-block font-medium ml-2 mt-3" %>
        <hr class="mt-6">
      <% end %>
    <% end %>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with model: book do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="m-auto">
    <div class="flex justify-between">
      <div>
        <div class="my-5">
          <%= form.label :title %>
          <%= form.text_field :title, placeholder: "Harry Potter", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>
        <div class="my-5">
          <%= form.label :date_of_publication %>
          <%= form.date_field :date_of_publication, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>
        <div class="my-5">
          <%= form.label :pages %>
          <%= form.number_field :pages, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>
        <div class="my-5">
          <%= form.label :description %>
          <%= form.text_area :description, rows: 4, placeholder: "The book about adventures of young wizzards from school of wizzards Hogwart.", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>
      </div>
      <div>
        <div class="m-auto mt-28 flex-col content-center">
          <%= form.label :image %>
          <br>
          <br>
          <%= image_tag form.object.image_url, class: "object-cover h-58 w-36 rounded-lg" if form.object.cached_image_data %>
          <%= form.hidden_field :image, value: @book.cached_image_data %>
          <%= form.file_field :image %>
        </div>
      </div>
    </div>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-xl py-3 px-5 active:bg-blue-800 hover:bg-blue-700 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
  <%= link_to 'Back to books', books_path, class: "whitespace-nowrap active:bg-gray-200 rounded-xl py-3 px-5 bg-white inline-block font-medium mt-3 ml-2" %>
<% end %>

app/views/books/_show_comments.html.erb
<% if @book.comments.empty? %>
  <div class="py-2 bg-white rounded-xl">
    <p class="mx-2">No comments yet.</p>
  </div>
<% else %>
  <%= render @book.comments.order(id: :desc) %>
<% end %>

app/views/books/edit.html.erb
<div class="mx-auto md:w-2/3 w-full mb-12 bg-gray-100 text-black-500 px-3 py-2 font-medium rounded-3xl mt-20 py-8">
  <h1 class="font-bold text-2xl text-center">Editing book</h1>
  <%= render "form", book: @book %>
  <%= link_to "Show this book", @book, class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 rounded-xl py-3 px-5 bg-white inline-block font-medium mt-3" %>
</div>

app/views/books/index.html.erb
<div class="w-full m-auto">
  <div class="flex justify-between items-center mx-auto md:w-2/3 w-full mb-12 bg-gray-100 text-black-500 px-3 py-2 font-medium rounded-3xl mt-20 py-8">
    <h1 class="font-bold text-4xl">Books</h1>
    <%= link_to 'New Book', new_book_path, class: "whitespace-nowrap active:bg-blue-800 hover:bg-blue-700 bg-blue-600 rounded-xl py-3 px-5 text-white block font-medium" %>
  </div>
  <div class="min-w-full">
    <%= render @books %>
  </div>
</div>

app/views/books/new.html.erb
<div class="mx-auto md:w-2/3 w-full mb-12 bg-gray-100 text-black-500 px-3 py-2 font-medium rounded-3xl mt-20 py-8">
  <h1 class="font-bold text-2xl">New book</h1>
  <%= render "form", book: @book %>
</div>

app/views/books/show.html.erb
<div class="mx-auto md:w-2/3 w-full mb-12 bg-gray-100 text-black-500 px-3 py-2 font-medium rounded-3xl mt-28 py-8">
  <h1 class="font-bold text-2xl text-center">Show Book: <%= @book.title %> </h1>
  <div class="m-auto">
    <div class="flex justify-between">
      <div>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl bg-gray-100 w-36">Title:</strong>
          <br>
          <span><%= @book.title %></span>
        </p>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl bg-gray-100 w-36">Pages:</strong>
          <br>
          <span><%= @book.pages %></span>
        </p>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl bg-gray-100 w-36">Date of publication:</strong>
          <br>
          <span><%= @book.date_of_publication.strftime("%d/%m/%Y") %></span>
        </p>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl bg-gray-100 w-36">Description:</strong>
          <br>
          <span><%= @book.description %></span>
        </p>
        <p class="my-5">
          <strong class="py-1 inline-block w-36 rounded-xl bg-gray-100 w-36">Comments:</strong>
          <br>
          <span><%= render partial: 'show_comments' %></span>
          <strong class="py-2 inline-block w-36 rounded-xl bg-gray-100 w-36">Add comment:</strong>
          <span><%= render partial: 'comments/form', locals: { book: @book } %></span>
        </p>
      </div>
      <div class="m-auto mt-28 flex content-center">
        <% if @book.image_url %>
          <%= image_tag @book.image_url, class: "object-cover h-58 w-36 rounded-lg" %>
        <% else %>
          <%= image_tag("book.jpeg", class: "object-cover h-58 w-36 rounded-lg") %>
        <% end %>
      </div>
    </div>
    <div class="flex justify-start flex-wrap gap-2">
      <% if current_user.admin? %>
        <%= link_to 'Edit this book', edit_book_path(@book), class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 mt-2 rounded-xl py-3 px-5 bg-white inline-block font-medium" %>
        <div class="inline-block">
          <%= button_to 'Delete this book', book_path(@book), method: :delete, class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 mt-2 rounded-xl py-3 px-5 bg-white font-medium" %>
        </div>
      <% end %>
      <%= link_to 'Back to books', books_path, class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 mt-2 rounded-xl py-3 px-5 bg-white font-medium" %>
      <%= button_to "Add to my books", users_books_path(book_id: @book.id, user_id: current_user.id), method: :post, class: "whitespace-nowrap active:bg-gray-200 hover:bg-gray-50 mt-2 rounded-xl py-3 px-5 bg-white font-medium" %>
    </div>
  </div>